nodeLinker: node-modules

npmScopes:
  ngfk:
    npmPublishRegistry: 'https://npm.ngfk.dev/'
    npmRegistryServer: 'https://npm.ngfk.dev/'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.6.0.cjs
