services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: ngfk_administration
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

  app:
    image: node:22.6.0
    working_dir: /app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database/ngfk_administration
    ports:
      - 4000:4000
    tty: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command:
      - /bin/sh
      - -cx
      - |
        npm i -g bun@1.1.24
        bun install
        bun run db:push
        bun run serve

volumes:
  database:
  node_modules:
